services:
    app.form.type.translation:
        class: CoreBundle\Form\Type\TranslationType
        arguments:
            - '@doctrine'
            - '@gedmo.listener.translatable'
            - '%form_translations%'
        tags:
            - { name: form.type }