location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /rest/location/

view:
    resource: "@ViewBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"